config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers:{ 
    :registrations => 'accounts/registrations', #登録用のコントローラ    
    :sessions => 'accounts/sessions' #ログイン用のコントローラ 
    }
  resources :accounts, only:[:index]
    devise_scope :account do
      root to: "devise/sessions#new"
    end
    resources :entries do
      resources :comments
    end
end

app/models/entry.rb
class Entry < ApplicationRecord
    has_many :comments
    has_many :timelines
    belongs_to :createby, class_name: "Account"
    accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank

    validates :title, presence: true 
    validates :contents, presence: true 

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

    def index
        @entries = Entry.all
        @search = Entry.ransack(params[:q]) 
        @result = @search.result
    end


    def new
        @entry = Entry.new
    end

    def create
        @entry = Entry.new(create_params)
        @entry.createby_id = current_account.id

        if @entry.save
            flash[:info] = "新しいエントリーを登録しました"
            redirect_to entries_path
        else
            render "new"
        end
    end

    def show
        @entry = Entry.find(params[:id])
        @comments = @entry.comments.all
        @comment = @entry.comments.new
    end

    def edit
        @entry = Entry.find(params[:id])
    end

    def update
        @entry = Entry.find(params[:id])

        if @entry.update_attributes(create_params)
            flash[:info] = "新しいエントリーを更新しました"
            redirect_to entries_path
        else
            render "new"
        end
    end

    def destroy
        @entry = Entry.find(params[:id])
        @entry.destroy
        redirect_to entries_path
    end

    private
        def create_params
            params.require(:entry).permit(:title,:contents)
        end

    

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edit.html.haml
.container
    .row.py-4
        .col-3
            .list-group.list-group-flush
                = link_to "エントリー一覧", entries_path, class:"list-group-item .text-black"
                = link_to "エントリー登録", new_entry_path, class:"list-group-item .text-black"
                = link_to "メンバー一覧", accounts_path, class:"list-group-item .text-black"
        .col-9.text-gray
            %h4.py-3 エントリー編集
            = simple_form_for @entry do |f|
                .form-group
                    = f.input :title,required: true,autofocus: true,input_html: { class:"form-control" }
                .form-group
                    = f.input :contents,required: true,autofocus: true,input_html: { class:"form-control",rows: 20  }
                .form-group
                    = f.submit :submit,class:"btn btn-primary"

app/views/entries/index.html.haml
.container
    .row.py-4
        .col-3
            .list-group.list-group-flush
                = link_to "エントリー一覧", entries_path, class:"list-group-item .text-black"
                = link_to "エントリー登録", new_entry_path, class:"list-group-item .text-black"
                = link_to "メンバー一覧", accounts_path, class:"list-group-item .text-black"
        .col-9.text-gray
            %h4.py-3 エントリー一覧
            = search_form_for @search do |f|
                .input-group.mb-4
                    = f.text_field :title_or_contents_cont, class:"form-control"
                    .input-group-append
                        = f.submit "フィルター", class:"btn btn-info"
            - if @result.any?
                - @result.order(id: "DESC").each do |entry|
                    = link_to entry_path(entry) do
                        .card.shadow-sm.mb-2.link-text-black
                            .card-body
                                %small #{entry.created_at.strftime('%Y/%m/%d %H:%M')} 作者：#{entry.createby.dispname}
                                %h5 [##{entry.id}] #{entry.title}
                                #{entry.contents}
            - else
                - @entries.order(id: "DESC").each do |entry|
                    = link_to entry_path(entry) do
                        .card.shadow-sm.mb-2.link-text-black
                            .card-body
                                %small #{entry.created_at.strftime('%Y/%m/%d %H:%M')} 作者：#{entry.createby.dispname}
                                %h5 #{entry.title}
                                %p #{entry.contents}

app/views/entries/new.html.haml
.container
    .row.py-4
        .col-3
            .list-group.list-group-flush
                = link_to "エントリー一覧", entries_path, class:"list-group-item .text-black"
                = link_to "エントリー登録", new_entry_path, class:"list-group-item .text-black"
                %a.list-group-item.text-black(href="#") エントリー検索
                %a.list-group-item.text-black(href="#") アカウント設定
        .col-9.text-gray
            %h4.py-3 エントリー登録
            = simple_form_for @entry do |f|
                .form-group
                    = f.input :title,required: true,autofocus: true,input_html: { class:"form-control" }
                .form-group
                    = f.input :contents,required: true,autofocus: true,input_html: { class:"form-control" }
                .form-group
                    = f.submit :submit,class:"btn btn-primary"

app/views/entries/show.html.haml
.container
    .row.py-4
        .col-3
            .list-group.list-group-flush
                = link_to "エントリー一覧", entries_path, class:"list-group-item .text-black"
                = link_to "エントリー登録", new_entry_path, class:"list-group-item .text-black"
                = link_to "メンバー一覧", accounts_path, class:"list-group-item .text-black"
        .col-9.text-gray
            .pt-3
                = link_to "←戻る", entries_path
            %small 作者：#{@entry.createby.dispname}
            .d-flex.align-items-center
                %h4.pb-1.d-inline.mr-auto [##{@entry.id}] #{@entry.title}
                - if @entry.createby == current_account
                    = link_to "編集", edit_entry_path(@entry),class:"btn btn-info mr-1"
                    = link_to "削除", entry_path(@entry),class:"btn btn-info",method: :delete
            .py-3
                .card.border-0.bg-light.mb-1
                    .card-body
                        = simple_format(@entry.contents)
            .box
                %strong コメント
            - @comments.order(id: "DESC").each do |comment|
                %small #{comment.created_at.strftime('%Y/%m/%d %H:%M')} #{comment.commenter.dispname}
                %hr.divider/
                .py-1.pb-2
                    = simple_format(comment.contents)
            = simple_form_for @comment, url: entry_comments_path(@entry) do |f|
                .form-group
                    = f.input :contents,required: true,input_html: { class:"form-control" },label:false
                .form-group
                    = f.submit :submit,class:"btn btn-primary"